<a href="https://colab.research.google.com/github/Pavanimale36/datascience/blob/main/employeedate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("/content/employee_attendance (1).csv")
df

  employee_name  login_date login_time  working_hours
0          Ravi  2024-02-10   08:45:30              8
1         Priya  2024-03-15   09:10:15              9
2       Karthik  2024-05-20   08:55:45              8
3        Anjali  2024-07-08   09:25:10              7
4        Vikram  2024-11-25   08:30:20              9

In [3]:
df["login_date"]=pd.to_datetime(df["login_date"])
df

  employee_name login_date login_time  working_hours
0          Ravi 2024-02-10   08:45:30              8
1         Priya 2024-03-15   09:10:15              9
2       Karthik 2024-05-20   08:55:45              8
3        Anjali 2024-07-08   09:25:10              7
4        Vikram 2024-11-25   08:30:20              9

In [4]:
df["year"]=df["login_date"].dt.year
df["month"]=df["login_date"].dt.month
df["day"]=df["login_date"].dt.day
df

  employee_name login_date login_time  working_hours  year  month  day
0          Ravi 2024-02-10   08:45:30              8  2024      2   10
1         Priya 2024-03-15   09:10:15              9  2024      3   15
2       Karthik 2024-05-20   08:55:45              8  2024      5   20
3        Anjali 2024-07-08   09:25:10              7  2024      7    8
4        Vikram 2024-11-25   08:30:20              9  2024     11   25

In [5]:
df["month_name"]=df["login_date"].dt.month_name()
df

,employee_name,login_date,login_time,working_hours,year,month,day,month_name
0,Ravi,2024-02-10,08:45:30,8,2024,2,10,February
1,Priya,2024-03-15,09:10:15,9,2024,3,15,March
2,Karthik,2024-05-20,08:55:45,8,2024,5,20,May
3,Anjali,2024-07-08,09:25:10,7,2024,7,8,July
4,Vikram,2024-11-25,08:30:20,9,2024,11,25,November

In [6]:
df["day_name"]=df["login_date"].dt.day_name()
df

,employee_name,login_date,login_time,working_hours,year,month,day,month_name,day_name
0,Ravi,2024-02-10,08:45:30,8,2024,2,10,February,Saturday
1,Priya,2024-03-15,09:10:15,9,2024,3,15,March,Friday
2,Karthik,2024-05-20,08:55:45,8,2024,5,20,May,Monday
3,Anjali,2024-07-08,09:25:10,7,2024,7,8,July,Monday
4,Vikram,2024-11-25,08:30:20,9,2024,11,25,November,Monday

In [7]:
earliest_date=df["login_date"].min()
df

,employee_name,login_date,login_time,working_hours,year,month,day,month_name,day_name
0,Ravi,2024-02-10,08:45:30,8,2024,2,10,February,Saturday
1,Priya,2024-03-15,09:10:15,9,2024,3,15,March,Friday
2,Karthik,2024-05-20,08:55:45,8,2024,5,20,May,Monday
3,Anjali,2024-07-08,09:25:10,7,2024,7,8,July,Monday
4,Vikram,2024-11-25,08:30:20,9,2024,11,25,November,Monday

In [8]:
largest_date=df["login_date"].max()
df

,employee_name,login_date,login_time,working_hours,year,month,day,month_name,day_name
0,Ravi,2024-02-10,08:45:30,8,2024,2,10,February,Saturday
1,Priya,2024-03-15,09:10:15,9,2024,3,15,March,Friday
2,Karthik,2024-05-20,08:55:45,8,2024,5,20,May,Monday
3,Anjali,2024-07-08,09:25:10,7,2024,7,8,July,Monday
4,Vikram,2024-11-25,08:30:20,9,2024,11,25,November,Monday

In [9]:
max_hours_emplyee=df.loc[df["working_hours"].idxmax()]
df

,employee_name,login_date,login_time,working_hours,year,month,day,month_name,day_name
0,Ravi,2024-02-10,08:45:30,8,2024,2,10,February,Saturday
1,Priya,2024-03-15,09:10:15,9,2024,3,15,March,Friday
2,Karthik,2024-05-20,08:55:45,8,2024,5,20,May,Monday
3,Anjali,2024-07-08,09:25:10,7,2024,7,8,July,Monday
4,Vikram,2024-11-25,08:30:20,9,2024,11,25,November,Monday