<a href="https://colab.research.google.com/github/Pavanimale36/datascience/blob/main/OneHotEncoded.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import seaborn as sns
from sklearn.preprocessing import OneHotEncoder
df=sns.load_dataset("tips")

In [11]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
X=df[["sex"]]

In [ ]:
encoder=OneHotEncoder(sparse_output=False)
encoded=encoder.fit_transform(X)
print(encoded)

In [15]:
print(encoder.get_feature_names_out())

['sex_Female' 'sex_Male']

In [8]:
import pandas as pd

In [ ]:
encoded_df=pd.DataFrame(
   encoded,
   columns=encoder.get_feature_names_out()
)
encoded_df

In [18]:
d=df.drop("sex",axis=1)

In [ ]:
d

In [20]:
final_df=pd.concat([d,encoded_df],axis=1)
final_df

     total_bill   tip smoker   day    time  size  sex_Female  sex_Male
0         16.99  1.01     No   Sun  Dinner     2         1.0       0.0
1         10.34  1.66     No   Sun  Dinner     3         0.0       1.0
2         21.01  3.50     No   Sun  Dinner     3         0.0       1.0
3         23.68  3.31     No   Sun  Dinner     2         0.0       1.0
4         24.59  3.61     No   Sun  Dinner     4         1.0       0.0
..          ...   ...    ...   ...     ...   ...         ...       ...
239       29.03  5.92     No   Sat  Dinner     3         0.0       1.0
240       27.18  2.00    Yes   Sat  Dinner     2         1.0       0.0
241       22.67  2.00    Yes   Sat  Dinner     2         0.0       1.0
242       17.82  1.75     No   Sat  Dinner     2         0.0       1.0
243       18.78  3.00     No  Thur  Dinner     2         1.0       0.0

[244 rows x 8 columns]