<a href="https://colab.research.google.com/github/Pavanimale36/datascience/blob/main/string_process.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import pandas as pd

In [19]:
df=pd.read_csv("/content/bank_customer_data.csv")
df

,customer_name,email,bank_name,account_type,account_number,balance,branch_city
0,SANthosh Chevuri,SANTHOSH@GMAIL.COM,hdfc bank,savings,ACC-1001,"Rs 1,25,000",hyderabad
1,RAJU kumar,RAJU@YAHOO.COM,ICICI BANK,CURRENT,ACC-1002,"$2,500",VIJAYAWADA
2,kiran REDDY,KIRAN@GMAIL.COM,axis bank,salary,ACC-1003,"Rs 75,000",vizag
3,SURESH BABU,SURESH@OUTLOOK.COM,SBI,SAVINGS,ACC-1004,"$10,000",GUNTUR
4,Lakshmi devi,LAKSHMI@GMAIL.COM,kotak bank,current,ACC-1005,"Rs 50,500",tirupati

In [20]:
df["email"]=df["email"].str.lower()
df

,customer_name,email,bank_name,account_type,account_number,balance,branch_city
0,SANthosh Chevuri,santhosh@gmail.com,hdfc bank,savings,ACC-1001,"Rs 1,25,000",hyderabad
1,RAJU kumar,raju@yahoo.com,ICICI BANK,CURRENT,ACC-1002,"$2,500",VIJAYAWADA
2,kiran REDDY,kiran@gmail.com,axis bank,salary,ACC-1003,"Rs 75,000",vizag
3,SURESH BABU,suresh@outlook.com,SBI,SAVINGS,ACC-1004,"$10,000",GUNTUR
4,Lakshmi devi,lakshmi@gmail.com,kotak bank,current,ACC-1005,"Rs 50,500",tirupati

In [21]:
df["customer_name"]=df["customer_name"].str.title()
df

,customer_name,email,bank_name,account_type,account_number,balance,branch_city
0,Santhosh Chevuri,santhosh@gmail.com,hdfc bank,savings,ACC-1001,"Rs 1,25,000",hyderabad
1,Raju Kumar,raju@yahoo.com,ICICI BANK,CURRENT,ACC-1002,"$2,500",VIJAYAWADA
2,Kiran Reddy,kiran@gmail.com,axis bank,salary,ACC-1003,"Rs 75,000",vizag
3,Suresh Babu,suresh@outlook.com,SBI,SAVINGS,ACC-1004,"$10,000",GUNTUR
4,Lakshmi Devi,lakshmi@gmail.com,kotak bank,current,ACC-1005,"Rs 50,500",tirupati

In [22]:
df["bank_name"]=df["bank_name"].str.upper()
df

,customer_name,email,bank_name,account_type,account_number,balance,branch_city
0,Santhosh Chevuri,santhosh@gmail.com,HDFC BANK,savings,ACC-1001,"Rs 1,25,000",hyderabad
1,Raju Kumar,raju@yahoo.com,ICICI BANK,CURRENT,ACC-1002,"$2,500",VIJAYAWADA
2,Kiran Reddy,kiran@gmail.com,AXIS BANK,salary,ACC-1003,"Rs 75,000",vizag
3,Suresh Babu,suresh@outlook.com,SBI,SAVINGS,ACC-1004,"$10,000",GUNTUR
4,Lakshmi Devi,lakshmi@gmail.com,KOTAK BANK,current,ACC-1005,"Rs 50,500",tirupati

In [23]:
df["account_type"]=df["account_type"].str.upper()
df

,customer_name,email,bank_name,account_type,account_number,balance,branch_city
0,Santhosh Chevuri,santhosh@gmail.com,HDFC BANK,SAVINGS,ACC-1001,"Rs 1,25,000",hyderabad
1,Raju Kumar,raju@yahoo.com,ICICI BANK,CURRENT,ACC-1002,"$2,500",VIJAYAWADA
2,Kiran Reddy,kiran@gmail.com,AXIS BANK,SALARY,ACC-1003,"Rs 75,000",vizag
3,Suresh Babu,suresh@outlook.com,SBI,SAVINGS,ACC-1004,"$10,000",GUNTUR
4,Lakshmi Devi,lakshmi@gmail.com,KOTAK BANK,CURRENT,ACC-1005,"Rs 50,500",tirupati

In [24]:
df["balance"]=df["balance"].str.replace("Rs ","", regex=False)
df["balance"]=df["balance"].str.replace("$","", regex=False)
df["balance"]=df["balance"].str.replace(",","", regex=False)
df

,customer_name,email,bank_name,account_type,account_number,balance,branch_city
0,Santhosh Chevuri,santhosh@gmail.com,HDFC BANK,SAVINGS,ACC-1001,125000,hyderabad
1,Raju Kumar,raju@yahoo.com,ICICI BANK,CURRENT,ACC-1002,2500,VIJAYAWADA
2,Kiran Reddy,kiran@gmail.com,AXIS BANK,SALARY,ACC-1003,75000,vizag
3,Suresh Babu,suresh@outlook.com,SBI,SAVINGS,ACC-1004,10000,GUNTUR
4,Lakshmi Devi,lakshmi@gmail.com,KOTAK BANK,CURRENT,ACC-1005,50500,tirupati

In [25]:
df["balance"]=df["balance"].astype(int)
df

,customer_name,email,bank_name,account_type,account_number,balance,branch_city
0,Santhosh Chevuri,santhosh@gmail.com,HDFC BANK,SAVINGS,ACC-1001,125000,hyderabad
1,Raju Kumar,raju@yahoo.com,ICICI BANK,CURRENT,ACC-1002,2500,VIJAYAWADA
2,Kiran Reddy,kiran@gmail.com,AXIS BANK,SALARY,ACC-1003,75000,vizag
3,Suresh Babu,suresh@outlook.com,SBI,SAVINGS,ACC-1004,10000,GUNTUR
4,Lakshmi Devi,lakshmi@gmail.com,KOTAK BANK,CURRENT,ACC-1005,50500,tirupati

In [26]:
df["user_name"]=df["email"].str.split("@").str[0]
df

,customer_name,email,bank_name,account_type,account_number,balance,branch_city,user_name
0,Santhosh Chevuri,santhosh@gmail.com,HDFC BANK,SAVINGS,ACC-1001,125000,hyderabad,santhosh
1,Raju Kumar,raju@yahoo.com,ICICI BANK,CURRENT,ACC-1002,2500,VIJAYAWADA,raju
2,Kiran Reddy,kiran@gmail.com,AXIS BANK,SALARY,ACC-1003,75000,vizag,kiran
3,Suresh Babu,suresh@outlook.com,SBI,SAVINGS,ACC-1004,10000,GUNTUR,suresh
4,Lakshmi Devi,lakshmi@gmail.com,KOTAK BANK,CURRENT,ACC-1005,50500,tirupati,lakshmi

In [27]:
df["domain"]=df["email"].str.split("@").str[1]
df

,customer_name,email,bank_name,account_type,account_number,balance,branch_city,user_name,domain
0,Santhosh Chevuri,santhosh@gmail.com,HDFC BANK,SAVINGS,ACC-1001,125000,hyderabad,santhosh,gmail.com
1,Raju Kumar,raju@yahoo.com,ICICI BANK,CURRENT,ACC-1002,2500,VIJAYAWADA,raju,yahoo.com
2,Kiran Reddy,kiran@gmail.com,AXIS BANK,SALARY,ACC-1003,75000,vizag,kiran,gmail.com
3,Suresh Babu,suresh@outlook.com,SBI,SAVINGS,ACC-1004,10000,GUNTUR,suresh,outlook.com
4,Lakshmi Devi,lakshmi@gmail.com,KOTAK BANK,CURRENT,ACC-1005,50500,tirupati,lakshmi,gmail.com

In [28]:
df["branch_code"]=df["branch_city"].str[:3]
df

,customer_name,email,bank_name,account_type,account_number,balance,branch_city,user_name,domain,branch_code
0,Santhosh Chevuri,santhosh@gmail.com,HDFC BANK,SAVINGS,ACC-1001,125000,hyderabad,santhosh,gmail.com,hyd
1,Raju Kumar,raju@yahoo.com,ICICI BANK,CURRENT,ACC-1002,2500,VIJAYAWADA,raju,yahoo.com,VIJ
2,Kiran Reddy,kiran@gmail.com,AXIS BANK,SALARY,ACC-1003,75000,vizag,kiran,gmail.com,viz
3,Suresh Babu,suresh@outlook.com,SBI,SAVINGS,ACC-1004,10000,GUNTUR,suresh,outlook.com,GUN
4,Lakshmi Devi,lakshmi@gmail.com,KOTAK BANK,CURRENT,ACC-1005,50500,tirupati,lakshmi,gmail.com,tir